// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/service/salutespeech/proto/storage/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SmartSpeech_Upload_FullMethodName   = "/smartspeech.storage.v1.SmartSpeech/Upload"
	SmartSpeech_Download_FullMethodName = "/smartspeech.storage.v1.SmartSpeech/Download"
)

// SmartSpeechClient is the client API for SmartSpeech service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartSpeechClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error)
}

type smartSpeechClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartSpeechClient(cc grpc.ClientConnInterface) SmartSpeechClient {
	return &smartSpeechClient{cc}
}

func (c *smartSpeechClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SmartSpeech_ServiceDesc.Streams[0], SmartSpeech_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SmartSpeech_UploadClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

func (c *smartSpeechClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SmartSpeech_ServiceDesc.Streams[1], SmartSpeech_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SmartSpeech_DownloadClient = grpc.ServerStreamingClient[DownloadResponse]

// SmartSpeechServer is the server API for SmartSpeech service.
// All implementations must embed UnimplementedSmartSpeechServer
// for forward compatibility.
type SmartSpeechServer interface {
	Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error
	mustEmbedUnimplementedSmartSpeechServer()
}

// UnimplementedSmartSpeechServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSmartSpeechServer struct{}

func (UnimplementedSmartSpeechServer) Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedSmartSpeechServer) Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedSmartSpeechServer) mustEmbedUnimplementedSmartSpeechServer() {}
func (UnimplementedSmartSpeechServer) testEmbeddedByValue()                     {}

// UnsafeSmartSpeechServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartSpeechServer will
// result in compilation errors.
type UnsafeSmartSpeechServer interface {
	mustEmbedUnimplementedSmartSpeechServer()
}

func RegisterSmartSpeechServer(s grpc.ServiceRegistrar, srv SmartSpeechServer) {
	// If the following call panics, it indicates UnimplementedSmartSpeechServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SmartSpeech_ServiceDesc, srv)
}

func _SmartSpeech_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SmartSpeechServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SmartSpeech_UploadServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

func _SmartSpeech_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartSpeechServer).Download(m, &grpc.GenericServerStream[DownloadRequest, DownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SmartSpeech_DownloadServer = grpc.ServerStreamingServer[DownloadResponse]

// SmartSpeech_ServiceDesc is the grpc.ServiceDesc for SmartSpeech service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartSpeech_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartspeech.storage.v1.SmartSpeech",
	HandlerType: (*SmartSpeechServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _SmartSpeech_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _SmartSpeech_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/service/salutespeech/proto/storage/storage.proto",
}
