// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/service/salutespeech/proto/storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileChunk []byte                 `protobuf:"bytes,1,opt,name=file_chunk,json=fileChunk,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadRequest) GetFileChunk() []byte {
	if x != nil {
		return x.xxx_hidden_FileChunk
	}
	return nil
}

func (x *UploadRequest) SetFileChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_FileChunk = v
}

type UploadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileChunk []byte
}

func (b0 UploadRequest_builder) Build() *UploadRequest {
	m0 := &UploadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FileChunk = b.FileChunk
	return m0
}

type UploadResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestFileId string                 `protobuf:"bytes,1,opt,name=request_file_id,json=requestFileId,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UploadResponse) GetRequestFileId() string {
	if x != nil {
		return x.xxx_hidden_RequestFileId
	}
	return ""
}

func (x *UploadResponse) SetRequestFileId(v string) {
	x.xxx_hidden_RequestFileId = v
}

type UploadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RequestFileId string
}

func (b0 UploadResponse_builder) Build() *UploadResponse {
	m0 := &UploadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RequestFileId = b.RequestFileId
	return m0
}

type DownloadRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResponseFileId string                 `protobuf:"bytes,1,opt,name=response_file_id,json=responseFileId,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadRequest) GetResponseFileId() string {
	if x != nil {
		return x.xxx_hidden_ResponseFileId
	}
	return ""
}

func (x *DownloadRequest) SetResponseFileId(v string) {
	x.xxx_hidden_ResponseFileId = v
}

type DownloadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ResponseFileId string
}

func (b0 DownloadRequest_builder) Build() *DownloadRequest {
	m0 := &DownloadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResponseFileId = b.ResponseFileId
	return m0
}

type DownloadResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FileChunk []byte                 `protobuf:"bytes,1,opt,name=file_chunk,json=fileChunk,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DownloadResponse) GetFileChunk() []byte {
	if x != nil {
		return x.xxx_hidden_FileChunk
	}
	return nil
}

func (x *DownloadResponse) SetFileChunk(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_FileChunk = v
}

type DownloadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FileChunk []byte
}

func (b0 DownloadResponse_builder) Build() *DownloadResponse {
	m0 := &DownloadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FileChunk = b.FileChunk
	return m0
}

var File_internal_service_salutespeech_proto_storage_storage_proto protoreflect.FileDescriptor

const file_internal_service_salutespeech_proto_storage_storage_proto_rawDesc = "" +
	"\n" +
	"9internal/service/salutespeech/proto/storage/storage.proto\x12\x16smartspeech.storage.v1\".\n" +
	"\rUploadRequest\x12\x1d\n" +
	"\n" +
	"file_chunk\x18\x01 \x01(\fR\tfileChunk\"8\n" +
	"\x0eUploadResponse\x12&\n" +
	"\x0frequest_file_id\x18\x01 \x01(\tR\rrequestFileId\";\n" +
	"\x0fDownloadRequest\x12(\n" +
	"\x10response_file_id\x18\x01 \x01(\tR\x0eresponseFileId\"1\n" +
	"\x10DownloadResponse\x12\x1d\n" +
	"\n" +
	"file_chunk\x18\x01 \x01(\fR\tfileChunk2\xcd\x01\n" +
	"\vSmartSpeech\x12[\n" +
	"\x06Upload\x12%.smartspeech.storage.v1.UploadRequest\x1a&.smartspeech.storage.v1.UploadResponse\"\x00(\x01\x12a\n" +
	"\bDownload\x12'.smartspeech.storage.v1.DownloadRequest\x1a(.smartspeech.storage.v1.DownloadResponse\"\x000\x01Bb\n" +
	")ru.sberdevices.smartspeech.recognition.v1Z5github.com/sberdevices/smartspeech/storage/v1;storageb\x06proto3"

var file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_service_salutespeech_proto_storage_storage_proto_goTypes = []any{
	(*UploadRequest)(nil),    // 0: smartspeech.storage.v1.UploadRequest
	(*UploadResponse)(nil),   // 1: smartspeech.storage.v1.UploadResponse
	(*DownloadRequest)(nil),  // 2: smartspeech.storage.v1.DownloadRequest
	(*DownloadResponse)(nil), // 3: smartspeech.storage.v1.DownloadResponse
}
var file_internal_service_salutespeech_proto_storage_storage_proto_depIdxs = []int32{
	0, // 0: smartspeech.storage.v1.SmartSpeech.Upload:input_type -> smartspeech.storage.v1.UploadRequest
	2, // 1: smartspeech.storage.v1.SmartSpeech.Download:input_type -> smartspeech.storage.v1.DownloadRequest
	1, // 2: smartspeech.storage.v1.SmartSpeech.Upload:output_type -> smartspeech.storage.v1.UploadResponse
	3, // 3: smartspeech.storage.v1.SmartSpeech.Download:output_type -> smartspeech.storage.v1.DownloadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_service_salutespeech_proto_storage_storage_proto_init() }
func file_internal_service_salutespeech_proto_storage_storage_proto_init() {
	if File_internal_service_salutespeech_proto_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_service_salutespeech_proto_storage_storage_proto_rawDesc), len(file_internal_service_salutespeech_proto_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_service_salutespeech_proto_storage_storage_proto_goTypes,
		DependencyIndexes: file_internal_service_salutespeech_proto_storage_storage_proto_depIdxs,
		MessageInfos:      file_internal_service_salutespeech_proto_storage_storage_proto_msgTypes,
	}.Build()
	File_internal_service_salutespeech_proto_storage_storage_proto = out.File
	file_internal_service_salutespeech_proto_storage_storage_proto_goTypes = nil
	file_internal_service_salutespeech_proto_storage_storage_proto_depIdxs = nil
}
